// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace tp4.Migrations
{
    [DbContext(typeof(DatosContexto))]
    [Migration("20250507225345_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.4");

            modelBuilder.Entity("Pregunta", b =>
                {
                    b.Property<int>("PreguntaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Correcta")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Enunciado")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RespuestaA")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RespuestaB")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RespuestaC")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("PreguntaId");

                    b.ToTable("Preguntas");
                });

            modelBuilder.Entity("RespuestaExamen", b =>
                {
                    b.Property<int>("RespuestaExamenId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("EsCorrecta")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PreguntaId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ResultadoExamenId")
                        .HasColumnType("INTEGER");

                    b.HasKey("RespuestaExamenId");

                    b.HasIndex("PreguntaId");

                    b.HasIndex("ResultadoExamenId");

                    b.ToTable("RespuestasExamen");
                });

            modelBuilder.Entity("ResultadoExamen", b =>
                {
                    b.Property<int>("ResultadoExamenId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Alumno")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("NotaFinal")
                        .HasColumnType("REAL");

                    b.Property<int>("RespuestasCorrectas")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TotalPreguntas")
                        .HasColumnType("INTEGER");

                    b.HasKey("ResultadoExamenId");

                    b.ToTable("ResultadosExamen");
                });

            modelBuilder.Entity("RespuestaExamen", b =>
                {
                    b.HasOne("Pregunta", "Pregunta")
                        .WithMany()
                        .HasForeignKey("PreguntaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ResultadoExamen", "ResultadoExamen")
                        .WithMany()
                        .HasForeignKey("ResultadoExamenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pregunta");

                    b.Navigation("ResultadoExamen");
                });
#pragma warning restore 612, 618
        }
    }
}
