// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using tp4.Datos;

#nullable disable

namespace tp4.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.6");

            modelBuilder.Entity("tp4.Modelos.Pregunta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Enunciado")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("OpcionA")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("OpcionB")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("OpcionC")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<char>("RespuestaCorrecta")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Preguntas");
                });

            modelBuilder.Entity("tp4.Modelos.RespuestaExamen", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Correcta")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PreguntaId")
                        .HasColumnType("INTEGER");

                    b.Property<char>("RespuestaAlumno")
                        .HasColumnType("TEXT");

                    b.Property<int>("ResultadoExamenId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PreguntaId");

                    b.HasIndex("ResultadoExamenId");

                    b.ToTable("RespuestasExamen");
                });

            modelBuilder.Entity("tp4.Modelos.ResultadoExamen", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Correctas")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NombreAlumno")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("NotaFinal")
                        .HasColumnType("REAL");

                    b.Property<int>("Total")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("ResultadosExamen");
                });

            modelBuilder.Entity("tp4.Modelos.RespuestaExamen", b =>
                {
                    b.HasOne("tp4.Modelos.Pregunta", "Pregunta")
                        .WithMany("Respuestas")
                        .HasForeignKey("PreguntaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("tp4.Modelos.ResultadoExamen", "ResultadoExamen")
                        .WithMany("Respuestas")
                        .HasForeignKey("ResultadoExamenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pregunta");

                    b.Navigation("ResultadoExamen");
                });

            modelBuilder.Entity("tp4.Modelos.Pregunta", b =>
                {
                    b.Navigation("Respuestas");
                });

            modelBuilder.Entity("tp4.Modelos.ResultadoExamen", b =>
                {
                    b.Navigation("Respuestas");
                });
#pragma warning restore 612, 618
        }
    }
}
