// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using servidor.Modelos;

#nullable disable

namespace servidor.Migrations
{
    [DbContext(typeof(TiendaContext))]
    partial class TiendaContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.5");

            modelBuilder.Entity("servidor.Modelos.Compra", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ApellidoCliente")
                        .HasColumnType("TEXT");

                    b.Property<string>("EmailCliente")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("TEXT");

                    b.Property<string>("NombreCliente")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Total")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Compras");
                });

            modelBuilder.Entity("servidor.Modelos.ItemCompra", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Cantidad")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CompraId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("PrecioUnitario")
                        .HasColumnType("TEXT");

                    b.Property<int>("ProductoId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CompraId");

                    b.HasIndex("ProductoId");

                    b.ToTable("ItemsCompra");
                });

            modelBuilder.Entity("servidor.Modelos.Producto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descripcion")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImagenUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Precio")
                        .HasColumnType("TEXT");

                    b.Property<int>("Stock")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Productos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Descripcion = "Mouse RGB con 6 botones",
                            ImagenUrl = "/assets/Mouse_Gamer.jpeg",
                            Nombre = "Mouse Gamer",
                            Precio = 5000m,
                            Stock = 20
                        },
                        new
                        {
                            Id = 2,
                            Descripcion = "Switch blue",
                            ImagenUrl = "https://via.placeholder.com/150",
                            Nombre = "Teclado Mecánico",
                            Precio = 12000m,
                            Stock = 15
                        },
                        new
                        {
                            Id = 3,
                            Descripcion = "Bluetooth 5.0",
                            ImagenUrl = "https://via.placeholder.com/150",
                            Nombre = "Auriculares Inalámbricos",
                            Precio = 8000m,
                            Stock = 10
                        },
                        new
                        {
                            Id = 4,
                            Descripcion = "Full HD 75Hz",
                            ImagenUrl = "https://via.placeholder.com/150",
                            Nombre = "Monitor 24''",
                            Precio = 35000m,
                            Stock = 8
                        },
                        new
                        {
                            Id = 5,
                            Descripcion = "Ergonómica",
                            ImagenUrl = "https://via.placeholder.com/150",
                            Nombre = "Silla Gamer",
                            Precio = 45000m,
                            Stock = 5
                        },
                        new
                        {
                            Id = 6,
                            Descripcion = "i5 10ma gen",
                            ImagenUrl = "https://via.placeholder.com/150",
                            Nombre = "Notebook 15''",
                            Precio = 200000m,
                            Stock = 6
                        },
                        new
                        {
                            Id = 7,
                            Descripcion = "Android 11",
                            ImagenUrl = "https://via.placeholder.com/150",
                            Nombre = "Tablet",
                            Precio = 50000m,
                            Stock = 7
                        },
                        new
                        {
                            Id = 8,
                            Descripcion = "128GB",
                            ImagenUrl = "https://via.placeholder.com/150",
                            Nombre = "Smartphone",
                            Precio = 95000m,
                            Stock = 10
                        },
                        new
                        {
                            Id = 9,
                            Descripcion = "1080p",
                            ImagenUrl = "https://via.placeholder.com/150",
                            Nombre = "Webcam HD",
                            Precio = 7000m,
                            Stock = 12
                        },
                        new
                        {
                            Id = 10,
                            Descripcion = "NVMe",
                            ImagenUrl = "https://via.placeholder.com/150",
                            Nombre = "Disco SSD 1TB",
                            Precio = 30000m,
                            Stock = 9
                        });
                });

            modelBuilder.Entity("servidor.Modelos.ItemCompra", b =>
                {
                    b.HasOne("servidor.Modelos.Compra", "Compra")
                        .WithMany("Items")
                        .HasForeignKey("CompraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("servidor.Modelos.Producto", "Producto")
                        .WithMany()
                        .HasForeignKey("ProductoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Compra");

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("servidor.Modelos.Compra", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
