// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace tp4.Migrations
{
    [DbContext(typeof(ExamenDbContext))]
    [Migration("20250509034648_Inicial")]
    partial class Inicial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.4");

            modelBuilder.Entity("Pregunta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Enunciado")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("OpcionA")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("OpcionB")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("OpcionC")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<char>("RespuestaCorrecta")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Preguntas");
                });

            modelBuilder.Entity("RespuestaExamen", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("EsCorrecta")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PreguntaId")
                        .HasColumnType("INTEGER");

                    b.Property<char>("RespuestaSeleccionada")
                        .HasColumnType("TEXT");

                    b.Property<int>("ResultadoExamenId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PreguntaId");

                    b.HasIndex("ResultadoExamenId");

                    b.ToTable("Respuestas");
                });

            modelBuilder.Entity("ResultadoExamen", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("NombreAlumno")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("NotaFinal")
                        .HasColumnType("REAL");

                    b.Property<int>("TotalCorrectas")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TotalPreguntas")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Resultados");
                });

            modelBuilder.Entity("RespuestaExamen", b =>
                {
                    b.HasOne("Pregunta", "Pregunta")
                        .WithMany("Respuestas")
                        .HasForeignKey("PreguntaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ResultadoExamen", "ResultadoExamen")
                        .WithMany("Respuestas")
                        .HasForeignKey("ResultadoExamenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pregunta");

                    b.Navigation("ResultadoExamen");
                });

            modelBuilder.Entity("Pregunta", b =>
                {
                    b.Navigation("Respuestas");
                });

            modelBuilder.Entity("ResultadoExamen", b =>
                {
                    b.Navigation("Respuestas");
                });
#pragma warning restore 612, 618
        }
    }
}
