// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TP4App;

#nullable disable

namespace TP4.Migrations
{
    [DbContext(typeof(ExamenDbContext))]
    partial class ExamenDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.0");

            modelBuilder.Entity("TP4App.Pregunta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Enunciado")
                        .HasColumnType("TEXT");

                    b.Property<string>("OpcionA")
                        .HasColumnType("TEXT");

                    b.Property<string>("OpcionB")
                        .HasColumnType("TEXT");

                    b.Property<string>("OpcionC")
                        .HasColumnType("TEXT");

                    b.Property<char>("RespuestaCorrecta")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Preguntas");
                });

            modelBuilder.Entity("TP4App.RespuestaExamen", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("EsCorrecta")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PreguntaId")
                        .HasColumnType("INTEGER");

                    b.Property<char>("RespuestaDada")
                        .HasColumnType("TEXT");

                    b.Property<int>("ResultadoExamenId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PreguntaId");

                    b.HasIndex("ResultadoExamenId");

                    b.ToTable("Respuestas");
                });

            modelBuilder.Entity("TP4App.ResultadoExamen", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CantidadCorrectas")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NombreAlumno")
                        .HasColumnType("TEXT");

                    b.Property<double>("NotaFinal")
                        .HasColumnType("REAL");

                    b.Property<int>("TotalPreguntas")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Resultados");
                });

            modelBuilder.Entity("TP4App.RespuestaExamen", b =>
                {
                    b.HasOne("TP4App.Pregunta", "Pregunta")
                        .WithMany("Respuestas")
                        .HasForeignKey("PreguntaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TP4App.ResultadoExamen", "ResultadoExamen")
                        .WithMany("Respuestas")
                        .HasForeignKey("ResultadoExamenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pregunta");

                    b.Navigation("ResultadoExamen");
                });

            modelBuilder.Entity("TP4App.Pregunta", b =>
                {
                    b.Navigation("Respuestas");
                });

            modelBuilder.Entity("TP4App.ResultadoExamen", b =>
                {
                    b.Navigation("Respuestas");
                });
#pragma warning restore 612, 618
        }
    }
}
