// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace tp4.Migrations
{
    [DbContext(typeof(DatosContexto))]
    [Migration("20250508124714_ActualizacionModelo")]
    partial class ActualizacionModelo
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.4");

            modelBuilder.Entity("Pregunta", b =>
                {
                    b.Property<int>("PreguntaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Correcta")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Enunciado")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RespuestaA")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RespuestaB")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RespuestaC")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("PreguntaId");

                    b.ToTable("Preguntas");
                });

            modelBuilder.Entity("RespuestaExamen", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("EsCorrecta")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PreguntaId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RespuestaSeleccionada")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ResultadoExamenId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PreguntaId");

                    b.HasIndex("ResultadoExamenId");

                    b.ToTable("Respuestas");
                });

            modelBuilder.Entity("ResultadoExamen", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Alumno")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Correctas")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("TEXT");

                    b.Property<double>("Nota")
                        .HasColumnType("REAL");

                    b.Property<int>("Total")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Examenes");
                });

            modelBuilder.Entity("RespuestaExamen", b =>
                {
                    b.HasOne("Pregunta", "Pregunta")
                        .WithMany("Respuestas")
                        .HasForeignKey("PreguntaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ResultadoExamen", "ResultadoExamen")
                        .WithMany("Respuestas")
                        .HasForeignKey("ResultadoExamenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pregunta");

                    b.Navigation("ResultadoExamen");
                });

            modelBuilder.Entity("Pregunta", b =>
                {
                    b.Navigation("Respuestas");
                });

            modelBuilder.Entity("ResultadoExamen", b =>
                {
                    b.Navigation("Respuestas");
                });
#pragma warning restore 612, 618
        }
    }
}
