// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Servidor.Data;

#nullable disable

namespace servidor.Migrations
{
    [DbContext(typeof(TiendaContext))]
    partial class TiendaContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.5");

            modelBuilder.Entity("Servidor.Models.Carrito", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Carritos");
                });

            modelBuilder.Entity("Servidor.Models.Compra", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ApellidoCliente")
                        .HasColumnType("TEXT");

                    b.Property<string>("EmailCliente")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("TEXT");

                    b.Property<string>("NombreCliente")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Total")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Compras");
                });

            modelBuilder.Entity("Servidor.Models.DetalleCompra", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Cantidad")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CompraId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("PrecioUnitario")
                        .HasColumnType("TEXT");

                    b.Property<int>("ProductoId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CompraId");

                    b.HasIndex("ProductoId");

                    b.ToTable("DetallesCompras");
                });

            modelBuilder.Entity("Servidor.Models.ItemCarrito", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Cantidad")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CarritoId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProductoId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CarritoId");

                    b.HasIndex("ProductoId");

                    b.ToTable("ItemsCarrito");
                });

            modelBuilder.Entity("Servidor.Models.Producto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descripcion")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImagenUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Precio")
                        .HasColumnType("TEXT");

                    b.Property<int>("Stock")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Productos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Descripcion = "Modelo Retro 2012/2013",
                            ImagenUrl = "/imagenes/3a4bed5882aa0026981e07e2ee9c6ed2.jpg",
                            Nombre = "Camiseta de fútbol Inter",
                            Precio = 8000.00m,
                            Stock = 10
                        },
                        new
                        {
                            Id = 2,
                            Descripcion = "Modelo Retro 1999/2000",
                            ImagenUrl = "/imagenes/528af923e61317453e9a761674c5e040.jpg",
                            Nombre = "Camiseta de fútbol Real Madrid",
                            Precio = 9500.00m,
                            Stock = 5
                        },
                        new
                        {
                            Id = 3,
                            Descripcion = "Modelo Retro 1998/1999",
                            ImagenUrl = "/imagenes/03ddd2e5d92dbb21f0501f704bca1de9.jpg",
                            Nombre = "Camiseta de fútbol Boca Juniors",
                            Precio = 9000.00m,
                            Stock = 7
                        },
                        new
                        {
                            Id = 4,
                            Descripcion = "Modelo Retro 2013/2014",
                            ImagenUrl = "/imagenes/9c8af3ba7529610d89b06096247552fc.jpg",
                            Nombre = "Camiseta de fútbol Borussia Dortmund",
                            Precio = 4000.00m,
                            Stock = 8
                        },
                        new
                        {
                            Id = 5,
                            Descripcion = "Modelo Retro 2012",
                            ImagenUrl = "/imagenes/542a001d4f6b03edb143f320b220b5d7.jpg",
                            Nombre = "Camiseta de fútbol Atletico Tucumán",
                            Precio = 7000.00m,
                            Stock = 15
                        },
                        new
                        {
                            Id = 6,
                            Descripcion = "Modelo Retro ",
                            ImagenUrl = "/imagenes/7579afdf0e7e8cc92cd8bfd79c610381.jpg",
                            Nombre = "Camiseta de fútbol Selección Italia",
                            Precio = 8250.00m,
                            Stock = 3
                        },
                        new
                        {
                            Id = 7,
                            Descripcion = "Modelo Retro 1998/2000",
                            ImagenUrl = "/imagenes/a9184fa085b21f0ba123a9cd7103148d.jpg",
                            Nombre = "Camiseta de fútbol Real Madrid",
                            Precio = 7350.00m,
                            Stock = 6
                        },
                        new
                        {
                            Id = 8,
                            Descripcion = "Modelo Retro 1996",
                            ImagenUrl = "/imagenes/a452159f6193fe98782e42dd9687ffa4.jpg",
                            Nombre = "Camiseta de fútbol Riber Plate",
                            Precio = 9450.00m,
                            Stock = 4
                        },
                        new
                        {
                            Id = 9,
                            Descripcion = "Modelo Retro 2007",
                            ImagenUrl = "/imagenes/cd11d87f448389e60c7bb108796cfab7.jpg",
                            Nombre = "Camiseta de fútbol Boca Juniors",
                            Precio = 5550.00m,
                            Stock = 1
                        },
                        new
                        {
                            Id = 10,
                            Descripcion = "Modelo Retro 2012/2013",
                            ImagenUrl = "/imagenes/ce4b1803a674d7e715cc90b610366632.jpg",
                            Nombre = "Camiseta de fútbol Milan",
                            Precio = 5600.00m,
                            Stock = 12
                        });
                });

            modelBuilder.Entity("Servidor.Models.DetalleCompra", b =>
                {
                    b.HasOne("Servidor.Models.Compra", "Compra")
                        .WithMany("Detalles")
                        .HasForeignKey("CompraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Servidor.Models.Producto", "Producto")
                        .WithMany("Detalles")
                        .HasForeignKey("ProductoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Compra");

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("Servidor.Models.ItemCarrito", b =>
                {
                    b.HasOne("Servidor.Models.Carrito", null)
                        .WithMany("Items")
                        .HasForeignKey("CarritoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Servidor.Models.Producto", "Producto")
                        .WithMany()
                        .HasForeignKey("ProductoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("Servidor.Models.Carrito", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("Servidor.Models.Compra", b =>
                {
                    b.Navigation("Detalles");
                });

            modelBuilder.Entity("Servidor.Models.Producto", b =>
                {
                    b.Navigation("Detalles");
                });
#pragma warning restore 612, 618
        }
    }
}
