// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace tp4.Migrations
{
    [DbContext(typeof(DatosContexto))]
    [Migration("20250509234103_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.4");

            modelBuilder.Entity("Pregunta", b =>
                {
                    b.Property<int>("PreguntaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Correcta")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Enunciado")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RespuestaA")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RespuestaB")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RespuestaC")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("PreguntaId");

                    b.ToTable("Preguntas");
                });
#pragma warning restore 612, 618
        }
    }
}
